name: Events

on:
  push:
    branches: [main, master]
    paths:
      - "events/**"
      - ".github/workflows/events.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "events/**"
      - ".github/workflows/events.yml"

env:
  REGISTRY: "cr.selcloud.ru/relocator-events"
  IMAGE_NAME: "events-server"
  CONTAINER_NAME: "events-server-container"

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: "1.24"
  #         cache-dependency-path: go.sum
  #     - name: Build
  #       run: |
  #         cd events/
  #         go build -o ./bin/ -v ./...

  #     # - name: Test
  #     #   run: |
  #     #     cd events/
  #     #     go test -v ./...
  # linter:
  # name: lint
  # runs-on: ubuntu-latest
  # steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-go@v5
  #     with:
  #       go-version: "1.23"
  #       cache: false
  #   - name: golangci-lint
  #     uses: golangci/golangci-lint-action@v7
  #     with:
  #       # Require: The version of golangci-lint to use.
  #       # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
  #       # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
  #       version: v2.1.0

  #       # Optional: working directory, useful for monorepos
  #       working-directory: "events"

  #       # Optional: golangci-lint command line arguments.
  #       #
  #       # Note: By default, the `.golangci.yml` file should be at the root of the chat.
  #       # The location of the configuration file can be changed by using `--config=`
  #       args: --timeout=30m

  #       # Optional: show only new issues if it's a pull request. The default value is `false`.
  #       # only-new-issues: true

  #       # Optional: if set to true, then all caching functionality will be completely disabled,
  #       #           takes precedence over all other caching options.
  #       # skip-cache: true

  #       # Optional: if set to true, then the action won't cache or restore ~/go/pkg.
  #       # skip-pkg-cache: true

  #       # Optional: if set to true, then the action won't cache or restore ~/.cache/go-build.
  #       # skip-build-cache: true

  #       # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
  #       # install-mode: "goinstall"
  build-and-push-image:
    runs-on: ubuntu-latest
    # needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=${GITHUB_SHA::7}
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f events/Dockerfile events/

  deploy-image:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{  secrets.SSHKEY }}
          envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, CONTAINER_NAME
          script: |
            TAG_NAME=${GITHUB_SHA::7}
            docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}} $REGISTRY
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            docker run -d --name $CONTAINER_NAME  --network reloca -t $REGISTRY/$IMAGE_NAME:$TAG_NAME
             docker images "$REGISTRY/$IMAGE_NAME" --format '{{.Repository}}:{{.Tag}} {{.ID}}' \
            | awk -v keep="$REGISTRY/$IMAGE_NAME:$TAG_NAME" '$1!=keep {print $2}' \
            | xargs -r docker rmi -f || true
            

        