name: Front

on:
  push:
    branches: [main, master]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "front/**"
      - ".github/workflows/front.yml"

env:
  REGISTRY: "cr.selcloud.ru/relocator-events"
  IMAGE_NAME: "front-server"
  CONTAINER_NAME: "front-server-container"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # needs: build-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        run: docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=${GITHUB_SHA::7}
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f front/Dockerfile front/

  deploy-image:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: deploy to Selectel Cloud via SSH action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{  secrets.SSHKEY }}
          envs: IMAGE_NAME, REGISTRY, GITHUB_SHA, CONTAINER_NAME
          script: |
            TAG_NAME=${GITHUB_SHA::7}
            docker login -u ${{secrets.REGISTRY_USERNAME}} -p ${{secrets.REGISTRY_PASSWORD}} $REGISTRY
            docker stop $CONTAINER_NAME
            docker rm $CONTAINER_NAME
            docker run -d \
            --name "$CONTAINER_NAME" \
            --network reloca \
            -p 3000:80 \
            -t "$REGISTRY/$IMAGE_NAME:$TAG_NAME"
